# Generated by Django 6.0.5 on 2026-05-15 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='children',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'ELEVE'}, related_name='parents', to=settings.AUTH_USER_MODEL, verbose_name='Enfants (Élèves)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.school', verbose_name='Établissement'),
        ),
    ]
