# Generated by Django 6.0.5 on 2026-05-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_children_customuser_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Matricule'),
        ),
    ]
