# Generated by Django 6.0.5 on 2026-05-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_matricule'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cni_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de CNI'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cni_scan',
            field=models.FileField(blank=True, null=True, upload_to='cni_scans/', verbose_name='Scan CNI'),
        ),
    ]
