# Generated by Django 6.0.5 on 2026-08-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_cni_number_customuser_cni_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Salaire de base (FCFA)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taux horaire (FCFA/h)'),
        ),
    ]
