# Generated by Django 6.0.5 on 2026-08-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_base_salary_customuser_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='allowances',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Primes & Indemnités (FCFA)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cotisations & Déductions (FCFA)'),
        ),
    ]
