# Generated by Django 6.0.5 on 2026-07-20 16:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_teachingpointage_remark_teachingpointage_status'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name="Commentaire de l'enseignant"),
        ),
        migrations.AddField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date et heure de déclaration'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_validated',
            field=models.BooleanField(default=False, verbose_name="Validé par l'Admin"),
        ),
        migrations.AddField(
            model_name='attendance',
            name='motive',
            field=models.CharField(blank=True, choices=[('MALADIE', 'Maladie'), ('JUSTIFIEE', 'Absence justifiée'), ('NON_JUSTIFIEE', 'Absence non justifiée'), ('AUTRE', 'Autre')], max_length=20, null=True, verbose_name="Motif d'absence"),
        ),
        migrations.AddField(
            model_name='attendance',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name="Observation de l'Admin"),
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.subject', verbose_name='Matière'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('enrollment', 'date', 'subject')},
        ),
    ]
