# Generated by Django 6.0.5 on 2026-05-15 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('core', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom (ex: Trimestre 1, Semestre 1)')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='core.academicyear', verbose_name='Année Scolaire')),
            ],
            options={
                'verbose_name': 'Période (Trimestre/Semestre)',
                'verbose_name_plural': 'Périodes',
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name="Titre de l'évaluation")),
                ('type', models.CharField(choices=[('DEVOIR', 'Devoir'), ('COMPOSITION', 'Composition'), ('EXAMEN', 'Examen')], default='DEVOIR', max_length=20, verbose_name='Type')),
                ('date', models.DateField(verbose_name="Date de l'évaluation")),
                ('max_score', models.FloatField(default=20.0, verbose_name='Note sur (ex: 20)')),
                ('weight', models.FloatField(default=1.0, verbose_name='Poids de cette évaluation')),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academics.subjectallocation', verbose_name='Matière/Classe')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='evaluations.term', verbose_name='Période')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Note obtenue')),
                ('comments', models.CharField(blank=True, max_length=255, null=True, verbose_name='Appréciation')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='evaluations.assessment', verbose_name='Évaluation')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.enrollment', verbose_name='Élève inscrit')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Saisie par')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'unique_together': {('assessment', 'enrollment')},
            },
        ),
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_average', models.FloatField(blank=True, null=True, verbose_name='Moyenne générale')),
                ('rank', models.PositiveIntegerField(blank=True, null=True, verbose_name="Rang de l'élève")),
                ('teacher_comments', models.TextField(blank=True, null=True, verbose_name='Appréciation du titulaire')),
                ('headmaster_comments', models.TextField(blank=True, null=True, verbose_name='Appréciation du directeur')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié (Visible par parents/élèves)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='students.enrollment', verbose_name='Élève inscrit')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='evaluations.term', verbose_name='Période')),
            ],
            options={
                'verbose_name': 'Bulletin',
                'verbose_name_plural': 'Bulletins',
                'unique_together': {('enrollment', 'term')},
            },
        ),
    ]
