# Generated by Django 6.0.5 on 2026-05-15 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la matière')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Code abrégé (ex: MATHS)')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
            },
        ),
        migrations.CreateModel(
            name='SubjectAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.PositiveIntegerField(default=1, verbose_name='Coefficient')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_allocations', to='core.classroom', verbose_name='Classe')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='academics.subject', verbose_name='Matière')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'ENSEIGNANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to=settings.AUTH_USER_MODEL, verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Attribution de Matière',
                'verbose_name_plural': 'Attributions de Matières',
                'unique_together': {('subject', 'classroom')},
            },
        ),
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date du cours')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la leçon / Chapitre')),
                ('content', models.TextField(verbose_name='Contenu du cours dispensé')),
                ('homework', models.TextField(blank=True, null=True, verbose_name='Travail à faire (Devoirs)')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PUBLISHED', 'Publié (Visible par parents/élèves)')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to='academics.subjectallocation', verbose_name='Cours')),
            ],
            options={
                'verbose_name': 'Entrée Cahier de Texte',
                'verbose_name_plural': 'Entrées Cahier de Texte',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
