# Generated by Django 6.0.5 on 2026-05-16 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_timeslot_timetableentry'),
        ('core', '0002_smslog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingPointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('hours_count', models.PositiveIntegerField(default=1, verbose_name="Nombre d'heures effectuées")),
                ('topic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Chapitre/Sujet abordé')),
                ('is_validated', models.BooleanField(default=False, verbose_name="Validé par l'Admin")),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classroom', verbose_name='Classe enseignée')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject', verbose_name='Matière')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_pointages', to=settings.AUTH_USER_MODEL, verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Pointage Enseignant',
                'verbose_name_plural': 'Pointages Enseignants',
                'ordering': ['-date'],
            },
        ),
    ]
