# Generated by Django 6.0.5 on 2026-07-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingpointage',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name="Remarque de l'administration"),
        ),
        migrations.AddField(
            model_name='teachingpointage',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('VALIDATED', 'Validé'), ('REFUSED', 'Refusé')], default='PENDING', max_length=20, verbose_name='Statut'),
        ),
    ]
