# Generated by Django 6.0.5 on 2026-05-15 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_smslog'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du frais')),
                ('default_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant par défaut')),
                ('is_monthly', models.BooleanField(default=True, verbose_name='Frais mensuel ?')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_types', to='core.school')),
            ],
            options={
                'verbose_name': 'Type de Frais',
                'verbose_name_plural': 'Types de Frais',
            },
        ),
        migrations.CreateModel(
            name='FeeAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant personnalisé')),
                ('due_date', models.DateField(verbose_name="Date d'échéance")),
                ('is_paid', models.BooleanField(default=False)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_allocations', to='students.enrollment')),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.feetype')),
            ],
            options={
                'verbose_name': 'Frais Alloué',
                'verbose_name_plural': 'Frais Alloués',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('CASH', 'Espèces'), ('WAVE', 'Wave'), ('ORANGE_MONEY', 'Orange Money'), ('BANK', 'Virement Bancaire')], default='CASH', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Transaction (Wave/OM)')),
                ('fee_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.feeallocation')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
    ]
