# Generated by Django 6.0.5 on 2026-05-16 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_smslog'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la dépense')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Catégorie (ex: Salaire, Loyer, Matériel)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('description', models.TextField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.school')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date'],
            },
        ),
    ]
