# Generated by Django 6.0.5 on 2026-08-03 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_notification'),
        ('finance', '0003_income'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField(verbose_name='Mois (1-12)')),
                ('year', models.PositiveIntegerField(verbose_name='Année')),
                ('hours_worked', models.FloatField(default=0, verbose_name='Heures validées')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taux horaire (FCFA/h)')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Salaire fixe de base')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Primes (FCFA)')),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Retenues (FCFA)')),
                ('advances', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Avances / Acomptes (FCFA)')),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Heures supplémentaires (FCFA)')),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Salaire Net (FCFA)')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Statut du Paiement')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='core.school', verbose_name='Établissement')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'ENSEIGNANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to=settings.AUTH_USER_MODEL, verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Fiche de Paie',
                'verbose_name_plural': 'Fiches de Paie',
                'ordering': ['-year', '-month'],
                'unique_together': {('teacher', 'month', 'year')},
            },
        ),
    ]
