# Generated by Django 6.0.5 on 2026-05-15 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_number', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('SENT', 'Envoyé'), ('FAILED', 'Échec'), ('PENDING', 'En attente')], default='PENDING', max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('provider_response', models.TextField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='core.school')),
            ],
            options={
                'verbose_name': 'Log SMS',
                'verbose_name_plural': 'Logs SMS',
            },
        ),
    ]
