# Generated by Django 6.0.5 on 2026-06-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_smslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='level',
            field=models.CharField(blank=True, choices=[('CI', 'CI (Cours Initiation)'), ('CP', 'CP (Cours Préparatoire)'), ('CE1', 'CE1 (Cours Élémentaire 1)'), ('CE2', 'CE2 (Cours Élémentaire 2)'), ('CM1', 'CM1 (Cours Moyen 1)'), ('CM2', 'CM2 (Cours Moyen 2)'), ('6EME', '6ème'), ('5EME', '5ème'), ('4EME', '4ème'), ('3EME', '3ème'), ('SECONDE', 'Seconde'), ('PREMIERE', '1ère'), ('TERMINALE', 'Terminale')], max_length=10, null=True, verbose_name='Niveau'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='series',
            field=models.CharField(choices=[('S1', 'S1 (Maths-Sciences Physiques)'), ('S2', 'S2 (Sciences Naturelles)'), ('S3', 'S3 (Sciences et Technologies)'), ('L1', 'L1 (Lettres & Sciences Humaines)'), ('L2', 'L2 (Arabe & Sciences Humaines)'), ('S4', 'S4 (Sciences et Technologies Industrielles)'), ('STEG', 'STEG (Sciences et Technologies Éco. & Gestion)'), ('G', 'G (Gestion)'), ('AUCUNE', 'Aucune (Primaire / Collège)')], default='AUCUNE', max_length=10, verbose_name='Série (Lycée)'),
        ),
    ]
