# Generated by Django 6.0.5 on 2026-06-08 17:26

import datetime
from django.db import migrations

def create_cycles_and_timeslots(apps, schema_editor):
    School = apps.get_model('core', 'School')
    Cycle = apps.get_model('core', 'Cycle')
    TimeSlot = apps.get_model('academics', 'TimeSlot')

    school = School.objects.first()
    if not school:
        school = School.objects.create(name="SeneSchool Pilote", address="Sénégal")

    for cycle_name in ['PRIMAIRE', 'COLLEGE', 'LYCEE']:
        Cycle.objects.get_or_create(school=school, name=cycle_name)

    default_slots = [
        (datetime.time(8, 0), datetime.time(9, 0)),
        (datetime.time(9, 0), datetime.time(10, 0)),
        (datetime.time(10, 0), datetime.time(11, 0)),
        (datetime.time(11, 0), datetime.time(12, 0)),
        (datetime.time(15, 0), datetime.time(16, 0)),
        (datetime.time(16, 0), datetime.time(17, 0)),
        (datetime.time(17, 0), datetime.time(18, 0)),
    ]
    for start, end in default_slots:
        TimeSlot.objects.get_or_create(start_time=start, end_time=end)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_level_series_to_classroom'),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_cycles_and_timeslots),
    ]
