# Generated by Django 6.0.5 on 2026-08-02 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_create_default_cycles'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('event_type', models.CharField(choices=[('EXAM', 'Examen'), ('VACATION', 'Vacances'), ('REUNION', 'Réunion'), ('HOLIDAY', 'Jour Férié'), ('ACTIVITY', 'Activité Scolaire')], default='ACTIVITY', max_length=20, verbose_name="Type d'événement")),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('color', models.CharField(default='#3b82f6', max_length=7, verbose_name='Couleur hexadécimale')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.school', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': 'Événement Scolaire',
                'verbose_name_plural': 'Événements Scolaires',
                'ordering': ['start_date'],
            },
        ),
    ]
