# Generated by Django 6.0.5 on 2026-08-03 19:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_schoolevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolevent',
            options={'ordering': ['start_date'], 'verbose_name': 'Événement scolaire', 'verbose_name_plural': 'Événements scolaires'},
        ),
        migrations.AddField(
            model_name='schoolevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schoolevent',
            name='color',
            field=models.CharField(default='#3b82f6', max_length=10, verbose_name='Couleur'),
        ),
        migrations.AlterField(
            model_name='schoolevent',
            name='event_type',
            field=models.CharField(choices=[('EXAM', 'Examen / Évaluation'), ('VACATION', 'Vacances scolaires'), ('HOLIDAY', 'Jour férié'), ('REUNION', 'Réunion'), ('ACTIVITY', 'Activité scolaire'), ('CONSEIL', 'Conseil de classe'), ('PARENTS', 'Réunion parents-professeurs'), ('OTHER', 'Autre')], default='OTHER', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='schoolevent',
            name='title',
            field=models.CharField(max_length=200, verbose_name="Titre de l'événement"),
        ),
    ]
